### ISSUE TITLE
No elite card for the 1k zombie quest

### ISSUE THREAD

**Issue by michaelarlt** [XelaNull/7DTD-WhiteRiver_ToC#1]
its not possible to gain the elite card as a reward. I have checked the quest.xml and didnt find the questitem_toc_elitecard_name as a reward in line 114, which explains it. So is this a bug or is there any specific way to gain the elite card otherwise?

**Comment by XelaNull** [comment]
WhiteRiverToC__REQUIRED/quests.xml line 132 shows the player being given quest quest_reward_1000z as a reward for killing the 1,000 zombies. Then within the quest_reward_1000z on line 163 it shows the player receiving:

`<reward type="Item" id="questitem_toc_elitecard_name" value="1" />`

**Comment by XelaNull** [comment]
And just to elaborate on the above.. the 1,000z quest is now a Tier 5 Trader quest. So the only way to initiate the quest is for the player to achieve Tier 5 quests with the Trader, and then have the Trader randomly offer the 1,000z quest. The good news is every elite quest will return an elite card. So once you obtain the 1,000z elite card, its yours to reuse over and over.

**Comment by XelaNull** [comment]
I did find that the elite quest was not being offered by the Trader as a Tier 5 quest. I've fixed this in the A20_1.0i_rc2 version, and have tested that it does indeed reward an Elite card. Closing report of Issue as it's tested as working.
